import { supabaseAdmin } from '../db/supabase.js'

const dbStatus = { placed: 'PLACED', accepted: 'ACCEPTED', picked_up: 'PICKED_UP', in_transit: 'IN_TRANSIT', delivered: 'DELIVERED', cancelled: 'CANCELLED' }
const apiStatus = Object.fromEntries(Object.entries(dbStatus).map(([key, value]) => [value, key]))
const transitions = { placed: ['accepted','cancelled'], accepted: ['picked_up','cancelled'], picked_up: ['in_transit','cancelled'], in_transit: ['delivered','cancelled'], delivered: [], cancelled: [] }
export const toApiOrder = (row) => ({ ...row, status: apiStatus[row.status] || row.status.toLowerCase() })

export async function getOrder(id) { const { data, error } = await supabaseAdmin.from('delivery_requests').select('*').eq('id', id).single(); if (error) throw error; return toApiOrder(data) }
export async function createOrder(userId, payload) { const { data, error } = await supabaseAdmin.from('delivery_requests').insert({ ...payload, customer_id: userId, status: 'PLACED' }).select().single(); if (error) throw error; return toApiOrder(data) }
export async function listUserOrders(userId) { const { data, error } = await supabaseAdmin.from('delivery_requests').select('*').eq('customer_id', userId).order('created_at', { ascending: false }); if (error) throw error; return data.map(toApiOrder) }
export async function updateOrderStatus(id, nextStatus) { const current = await getOrder(id); if (!transitions[current.status]?.includes(nextStatus)) { const error = new Error(`Invalid status transition: ${current.status} -> ${nextStatus}`); error.status = 409; throw error } const { data, error } = await supabaseAdmin.from('delivery_requests').update({ status: dbStatus[nextStatus], updated_at: new Date().toISOString() }).eq('id', id).select().single(); if (error) throw error; await supabaseAdmin.from('order_status_history').insert({ request_id: id, status: nextStatus }); return toApiOrder(data) }
export async function assignNearestDriver(id, radiusKm) { const order = await getOrder(id); const { data: driver, error: rpcError } = await supabaseAdmin.rpc('find_nearest_available_driver', { target_lat: order.pickup_lat, target_lng: order.pickup_lng, radius_km: radiusKm }); if (rpcError) throw rpcError; if (!driver) { const error = new Error('No available driver found within the search radius'); error.status = 404; throw error } const { data, error } = await supabaseAdmin.from('delivery_requests').update({ assigned_driver_id: driver.profile_id, status: 'ACCEPTED', updated_at: new Date().toISOString() }).eq('id', id).select().single(); if (error) throw error; await supabaseAdmin.from('drivers').update({ available: false }).eq('id', driver.driver_id); await supabaseAdmin.from('order_status_history').insert({ request_id: id, status: 'accepted' }); return toApiOrder(data) }
