import { useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../auth/AuthContext'
import { useCompanyRequests, useCompanyVehicles, useCompanyDrivers } from '../hooks/useSupabaseData'
import { createInvoice, updateDeliveryRequest } from '../services/supabaseData'
import PageHeader from '../components/PageHeader'
import StatusBadge from '../components/StatusBadge'

export default function AdminRequestsRemote(){
  const {session}=useAuth(); const {data:requests,loading,refresh}=useCompanyRequests(session.partnerId); const {data:vehicles}=useCompanyVehicles(session.partnerId); const {data:drivers}=useCompanyDrivers(session.partnerId); const [selected,setSelected]=useState({}); const [error,setError]=useState(''); const [saving,setSaving]=useState(false)
  function choose(id,key,value){setSelected({...selected,[id]:{...selected[id],[key]:value}})}
  async function approve(request){const choice=selected[request.id]||{};if(!choice.vehicle)return setError('Select a vehicle for the request before approving it.');setSaving(true);setError('');try{await updateDeliveryRequest(request.id,{status:'VEHICLE_ASSIGNED',assigned_vehicle_id:choice.vehicle,assigned_driver_id:choice.driver||null});await createInvoice({request_id:request.id,invoice_number:`TX-${Date.now().toString().slice(-8)}`,amount_inr:request.quoted_price_inr||15000,status:'ISSUED'});await refresh()}catch(err){setError(err.message||'Unable to approve and assign this request.')}finally{setSaving(false)}}
  async function reject(request){setSaving(true);try{await updateDeliveryRequest(request.id,{status:'REJECTED'});await refresh()}catch(err){setError(err.message)}finally{setSaving(false)}}
  return <><PageHeader eyebrow="ADMIN / ORDER VERIFICATION" title="Incoming orders" description={`Only orders selected for ${session.partnerName} are shown.`}/>{error&&<div className="form-error">{error}</div>}<div className="admin-request-grid">{loading?<div className="panel empty-state">Loading Supabase requests...</div>:requests.length===0?<div className="panel empty-state">No orders are waiting for your company.</div>:requests.map(request=>{const choice=selected[request.id]||{};return <article className="panel admin-request-card" key={request.id}><div className="request-card-head"><div><div className="eyebrow">{request.id.slice(0,8)}</div><h2>{request.pickup} → {request.dropoff}</h2><span>Submitted {new Date(request.created_at).toLocaleString()}</span></div><StatusBadge>{request.status.replaceAll('_',' ')}</StatusBadge></div><div className="request-detail-grid"><div><small>PAYLOAD</small><b>{request.payload_weight_kg} kg</b></div><div><small>SIZE</small><b>{request.length_cm} × {request.width_cm} × {request.height_cm} cm</b></div><div><small>QUOTE</small><b>₹{Number(request.quoted_price_inr||0).toLocaleString('en-IN')}</b></div><div><small>VEHICLE</small><b>{request.assigned_vehicle?.vehicle_number||'Unassigned'}</b></div></div>{request.status==='PENDING_APPROVAL'&&<div className="request-card-footer"><select value={choice.vehicle||''} onChange={e=>choose(request.id,'vehicle',e.target.value)}><option value="">Select vehicle</option>{vehicles.map(vehicle=><option key={vehicle.id} value={vehicle.id}>{vehicle.vehicle_number} · {vehicle.plate_number}</option>)}</select><select value={choice.driver||''} onChange={e=>choose(request.id,'driver',e.target.value)}><option value="">Select driver</option>{drivers.map(driver=><option key={driver.profile_id} value={driver.profile_id}>{driver.profiles?.name||driver.driver_code}</option>)}</select><button className="button danger-button" disabled={saving} onClick={()=>reject(request)}>Reject</button><button className="button primary-button" disabled={saving} onClick={()=>approve(request)}>Approve & assign</button></div>}</article>})}</div>{vehicles.length===0&&<div className="empty-state">No vehicles available. <Link to="/admin/vehicles">Add a vehicle first →</Link></div>}</>
}
