import { useState } from 'react'
import { useAuth } from '../auth/AuthContext'
import PageHeader from '../components/PageHeader'
import { useCompanyDrivers, useCompanyVehicles } from '../hooks/useSupabaseData'
import { createDriverAccount } from '../services/supabaseData'

export default function AdminDriversRemote(){
  const {session}=useAuth(); const {data:drivers,loading,refresh}=useCompanyDrivers(session.partnerId); const {data:vehicles}=useCompanyVehicles(session.partnerId)
  const [form,setForm]=useState({name:'',email:'',phone:'',vehicleId:'',driverCode:''}); const [credentials,setCredentials]=useState(null); const [error,setError]=useState(''); const [saving,setSaving]=useState(false)
  async function submit(event){event.preventDefault();setError('');setCredentials(null);setSaving(true);try{const result=await createDriverAccount({...form,companyId:session.partnerId});setCredentials(result);setForm({name:'',email:'',phone:'',vehicleId:'',driverCode:''});await refresh()}catch(err){setError(err.message||'Unable to register driver.')}finally{setSaving(false)}}
  return <><PageHeader eyebrow="FLEET / DRIVER ACCESS" title={`${session.partnerName} drivers`} description="Live driver accounts registered to your transport company."/><div className="driver-admin-grid"><section className="panel"><div className="eyebrow">REGISTER DRIVER</div><h2>Create driver access</h2><form className="driver-form" onSubmit={submit}><label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Assigned vehicle<select value={form.vehicleId} onChange={e=>setForm({...form,vehicleId:e.target.value})}><option value="">No vehicle assigned</option>{vehicles.map(vehicle=><option key={vehicle.id} value={vehicle.id}>{vehicle.vehicle_number} · {vehicle.plate_number}</option>)}</select></label><label>Driver ID <small>(optional, generated if empty)</small><input value={form.driverCode} onChange={e=>setForm({...form,driverCode:e.target.value})}/></label>{error&&<div className="form-error">{error}</div>}<button className="button primary-button" disabled={saving}>{saving?'Creating account...':'Register driver & generate password'}</button></form>{credentials&&<div className="credential-card"><b>Driver credentials</b><span>Email: <strong>{credentials.email}</strong></span><span>Password: <strong>{credentials.password}</strong></span><small>Save these credentials. The driver can now sign in through the Driver app.</small></div>}</section><section className="panel"><div className="eyebrow">REGISTERED DRIVERS</div><h2>{loading?'Loading...':`${drivers.length} company drivers`}</h2>{drivers.map(driver=><div className="driver-row" key={driver.id}><div className="user-avatar">{driver.profiles?.name?.[0]||'D'}</div><div><b>{driver.profiles?.name||driver.driver_code}</b><span>{driver.driver_code} · {driver.status} · {session.partnerName}</span></div></div>)}</section></div></>
}
