import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../auth/AuthContext'
import { useCompanies } from '../hooks/useSupabaseData'
import { createDeliveryImage, createDeliveryRequest, uploadRequestImage } from '../services/supabaseData'

export default function CreateDeliveryRequestRemote(){
  const {session}=useAuth(); const navigate=useNavigate(); const {data:companies,loading}=useCompanies()
  const [form,setForm]=useState({pickup:'',dropoff:'',weight:'',length:'',width:'',height:'',notes:''}); const [companyId,setCompanyId]=useState(''); const [files,setFiles]=useState([]); const [error,setError]=useState(''); const [saving,setSaving]=useState(false)
  function change(e){setForm({...form,[e.target.name]:e.target.value})}
  async function submit(e){e.preventDefault(); setError(''); if(!companyId||!form.pickup||!form.dropoff||!form.weight||!form.length||!form.width||!form.height||!files.length)return setError('Complete all delivery fields, select a partner, and upload at least one image.'); setSaving(true); try{const company=companies.find(item=>item.id===companyId); const request=await createDeliveryRequest({customer_id:session.id,company_id:company.id,pickup:form.pickup,dropoff:form.dropoff,payload_weight_kg:Number(form.weight),length_cm:Number(form.length),width_cm:Number(form.width),height_cm:Number(form.height),notes:form.notes,status:'PENDING_APPROVAL',quoted_price_inr:company.base_price_inr||0,eta:company.eta_label||null}); for(const file of files){const path=await uploadRequestImage(session.id,request.id,file); await createDeliveryImage({request_id:request.id,storage_path:path,file_name:file.name})} navigate('/user/requests')}catch(err){setError(err.message)}finally{setSaving(false)}}
  return <><div className="user-hero compact-hero"><div><div className="eyebrow">NEW DELIVERY REQUEST</div><h1>Plan a delivery</h1><p>Compare transport partners and submit your shipment.</p></div></div><form className="request-form" onSubmit={submit}><section className="user-panel"><div className="form-section-title"><span className="step-number">1</span><div><h2>Delivery details</h2><p>Where should your product be collected and delivered?</p></div></div><div className="form-grid"><label>Pickup location<input name="pickup" value={form.pickup} onChange={change}/></label><label>Delivery location<input name="dropoff" value={form.dropoff} onChange={change}/></label><label>Package weight (kg)<input name="weight" type="number" value={form.weight} onChange={change}/></label><label>Delivery notes<textarea name="notes" value={form.notes} onChange={change}/></label></div></section><section className="user-panel"><div className="form-section-title"><span className="step-number">2</span><div><h2>Product size and images</h2><p>At least one product image is required.</p></div></div><div className="size-grid">{[['length','Length (cm)'],['width','Width (cm)'],['height','Height (cm)']].map(([name,label])=><label key={name}>{label}<input name={name} type="number" value={form[name]} onChange={change}/></label>)}</div><label className="upload-box"><input type="file" accept="image/*" multiple onChange={e=>setFiles(Array.from(e.target.files).slice(0,6))}/><b>Upload product images</b><small>PNG, JPG, or WEBP · Up to 6 images</small></label>{files.length>0&&<small>{files.length} image(s) selected</small>}</section><section className="user-panel"><div className="form-section-title"><span className="step-number">3</span><div><h2>Compare delivery partners</h2><p>Prices and ETA are provided by Supabase company records.</p></div></div><div className="partner-grid">{loading?<p>Loading partners...</p>:companies.map(company=><button type="button" key={company.id} className={`partner-card ${companyId===company.id?'selected':''}`} onClick={()=>setCompanyId(company.id)}><div className="partner-top"><span className="partner-logo">{company.name[0]}</span><span>{companyId===company.id?'✓ Selected':'Select'}</span></div><h3>{company.name}</h3><div className="partner-facts"><div><small>PRICE</small><b>₹{(company.base_price_inr||0).toLocaleString('en-IN')}</b></div><div><small>ETA</small><b>{company.eta_label||'To confirm'}</b></div><div><small>RATING</small><b>{company.rating||'—'}</b></div></div></button>)}</div></section>{error&&<div className="form-error">{error}</div>}<div className="request-submit"><span>{companyId?'Partner selected':'Select a partner to continue'}</span><button className="button primary-button" disabled={saving}>{saving?'Submitting...':'Submit delivery request →'}</button></div></form></>
}
