import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { registerAccount } from '../services/supabaseData'

export default function Signup(){
  const navigate=useNavigate(); const [role,setRole]=useState('user'); const [form,setForm]=useState({name:'',email:'',password:'',companyName:''}); const [error,setError]=useState(''); const [saving,setSaving]=useState(false)
  async function submit(event){event.preventDefault();setError('');setSaving(true);try{await registerAccount({...form,role});navigate('/login',{state:{message:'Account created. Sign in to continue.'}})}catch(err){setError(err.message||'Unable to create account.')}finally{setSaving(false)}}
  return <div className="login-page"><div className="login-brand"><span className="brand-mark">↗</span><span>Transporto<span className="accent">X</span></span></div><div className="login-card"><div className="eyebrow">FLEET OPERATIONS PLATFORM</div><h1>Create your account</h1><p className="login-copy">Choose how you will use TransportoX.</p><div className="role-tabs"><button type="button" className={role==='user'?'selected':''} onClick={()=>setRole('user')}>User</button><button type="button" className={role==='admin'?'selected':''} onClick={()=>setRole('admin')}>Admin</button></div><form onSubmit={submit}><label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email address<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label>{role==='admin'&&<label>Transport company name<input required value={form.companyName} onChange={e=>setForm({...form,companyName:e.target.value})}/></label>}<label>Password<input required minLength="8" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{error&&<div className="login-error">{error}</div>}<button className="button primary-button login-button" disabled={saving}>{saving?'Creating account...':'Create account'}</button></form><p className="signup-prompt">Already have an account? <Link to="/login">Sign in</Link></p></div><div className="login-footer">SECURE TRANSPORT OPERATIONS PLATFORM</div></div>
}
