import { useState } from 'react'
import { useParams } from 'react-router-dom'
import { useAuth } from '../auth/AuthContext'
import { useCompanyRequests, useCustomerRequests } from '../hooks/useSupabaseData'
import PageHeader from '../components/PageHeader'
import StatusBadge from '../components/StatusBadge'

function formatEta(value){if(!value)return 'Pending confirmation';const date=new Date(value);return Number.isNaN(date.getTime())?value:date.toLocaleString([], {dateStyle:'medium',timeStyle:'short'})}

export default function TrackingRemote(){
  const {id}=useParams(); const {session}=useAuth(); const remote=session.role==='admin'?useCompanyRequests(session.partnerId):useCustomerRequests(session.id); const [code,setCode]=useState(id||''); const [activeCode,setActiveCode]=useState(id||''); const normalizedCode=activeCode.trim().toLowerCase(); const request=remote.data.find(item=>{const requestId=item.id.toLowerCase();return requestId===normalizedCode||requestId.startsWith(normalizedCode)})||(!normalizedCode?remote.data[0]:null)
  function lookup(){setActiveCode(code.trim())}
  return <><PageHeader eyebrow="SHIPMENT STATUS / LIVE DATA" title="Shipment tracker" description="Inspect live order status and delivery milestones from Supabase."/><div className="tracking-wrap"><section className="tracking-search"><div><div className="eyebrow">ORDER LOOKUP</div><h2>Track your shipment</h2><p>Enter an order ID from your shipment history.</p></div><div className="search-action"><input value={code} onChange={e=>setCode(e.target.value)} onKeyDown={e=>e.key==='Enter'&&lookup()} placeholder="Paste order ID"/><button className="button primary-button" onClick={lookup}>Track shipment</button></div></section>{remote.loading?<div className="tracking-card">Loading live shipment...</div>:remote.error?<div className="tracking-card empty-state">Unable to load shipments. Please try again.</div>:request?<section className="tracking-card"><div className="tracking-top"><div><span className="eyebrow">ORDER ID</span><h2>{request.id}</h2><p>{request.pickup} <span>→</span> {request.dropoff}</p></div><StatusBadge>{request.status.replaceAll('_',' ')}</StatusBadge></div><div className="tracking-metrics"><div><span className="eyebrow">TRANSPORT COMPANY</span><b>{request.company?.name||'Company unavailable'}</b><small>Assigned delivery partner</small></div><div><span className="eyebrow">ESTIMATED ARRIVAL</span><b>{formatEta(request.eta)}</b><small>Last calculated delivery estimate</small></div><div><span className="eyebrow">PAYLOAD</span><b>{request.payload_weight_kg||0} kg</b><small>Assigned cargo weight</small></div></div><div className="tracking-timeline"><div className="eyebrow">DELIVERY MILESTONES</div><div className="tracking-steps"><span className={request.status!=='PENDING_APPROVAL'?'complete':''}>Request placed</span><span className={['VEHICLE_ASSIGNED','PICKED_UP','IN_TRANSIT','DELIVERED'].includes(request.status)?'complete':''}>Vehicle assigned</span><span className={['PICKED_UP','IN_TRANSIT','DELIVERED'].includes(request.status)?'complete':''}>In transit</span><span className={request.status==='DELIVERED'?'complete':''}>Delivered</span></div></div></section>:<div className="tracking-card empty-state">No shipment found for this account. Check the order ID and try again.</div>}</div></>
}
