import { useState } from 'react'
import PageHeader from '../components/PageHeader'
import StatusBadge from '../components/StatusBadge'
import { useAuth } from '../auth/AuthContext'
import { useCompanyVehicles } from '../hooks/useSupabaseData'
import { createCompanyVehicle } from '../services/supabaseData'

export default function VehiclesRemote(){
  const {session}=useAuth(); const {data:vehicles,loading,refresh}=useCompanyVehicles(session.partnerId); const [open,setOpen]=useState(false); const [error,setError]=useState(''); const [saving,setSaving]=useState(false); const [form,setForm]=useState({id:'',plate:'',type:'EV',capacity:''})
  async function submit(event){event.preventDefault();setError('');setSaving(true);try{await createCompanyVehicle({company_id:session.partnerId,vehicle_number:form.id.trim(),plate_number:form.plate.trim(),type:form.type,status:'AVAILABLE',capacity_kg:Number(form.capacity),current_load_kg:0,fuel_or_battery_pct:100,health_score:100});setForm({id:'',plate:'',type:'EV',capacity:''});setOpen(false);await refresh()}catch(err){setError(err.message||'Unable to add vehicle.')}finally{setSaving(false)}}
  return <><PageHeader eyebrow={`FLEET / ${session.partnerName?.toUpperCase()}`} title="Vehicle Fleet" description={`Only ${session.partnerName} vehicles are shown.`} action={<button className="button primary-button" onClick={()=>{setError('');setOpen(true)}}>＋ Add vehicle</button>}/><div className="panel table-panel"><div className="panel-heading"><h2>{loading?'Loading vehicles...':`${vehicles.length} company vehicles`}</h2><span className="muted">Live Supabase data</span></div><div className="table-wrap"><table><thead><tr><th>VEHICLE</th><th>PLATE</th><th>TYPE</th><th>STATUS</th><th>CAPACITY</th><th>HEALTH</th></tr></thead><tbody>{vehicles.map(vehicle=><tr key={vehicle.id}><td><b>{vehicle.vehicle_number}</b></td><td>{vehicle.plate_number}</td><td>{vehicle.type}</td><td><StatusBadge>{vehicle.status}</StatusBadge></td><td>{vehicle.capacity_kg} kg</td><td className="success-text">{vehicle.health_score}%</td></tr>)}</tbody></table></div></div>{open&&<div className="modal-backdrop"><form className="failure-modal vehicle-modal" onSubmit={submit}><button type="button" className="modal-close" onClick={()=>setOpen(false)}>×</button><div className="eyebrow">REGISTER VEHICLE</div><h2>{session.partnerName}</h2><label className="driver-form-label">Vehicle ID<input required value={form.id} onChange={e=>setForm({...form,id:e.target.value})}/></label><label className="driver-form-label">Plate number<input required value={form.plate} onChange={e=>setForm({...form,plate:e.target.value})}/></label><label className="driver-form-label">Capacity in kg<input required type="number" min="1" value={form.capacity} onChange={e=>setForm({...form,capacity:e.target.value})}/></label><label className="driver-form-label">Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>EV</option><option>DIESEL</option><option>HYBRID</option></select></label>{error&&<div className="form-error">{error}</div>}<button className="button primary-button wide" disabled={saving}>{saving?'Saving...':'Save vehicle'}</button></form></div>}</>
}
